<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class inicialesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // generame u seeder cone stos datos para la tabla tipo_mandamiento:
        // MANDAMIENTO DE APREHENSION ,ORDEN DE APREHENSION,PROFUGO KL80, MANDAMIENTO DE CAPTURA,MANDAMIENTO DE APREMIO

        $tiposMandamientos = [
            ['tipo_mandamiento' => 'MANDAMIENTO DE APREHENSION', 'estado_tipo_mandamiento' => 'ACTIVO', 'descripcion_tipo_mandamiento' => 'Mandamiento para la aprehensión de una persona.'],
            ['tipo_mandamiento' => 'ORDEN DE APREHENSION', 'estado_tipo_mandamiento' => 'ACTIVO', 'descripcion_tipo_mandamiento' => 'Orden emitida por una autoridad judicial para la aprehensión.'],
            ['tipo_mandamiento' => 'PROFUGO KL80', 'estado_tipo_mandamiento' => 'ACTIVO', 'descripcion_tipo_mandamiento' => 'Mandamiento para la captura de un prófugo.'],
            ['tipo_mandamiento' => 'MANDAMIENTO DE CAPTURA', 'estado_tipo_mandamiento' => 'ACTIVO', 'descripcion_tipo_mandamiento' => 'Mandamiento para la captura de una persona buscada por la justicia.'],
            ['tipo_mandamiento' => 'MANDAMIENTO DE APREMIO', 'estado_tipo_mandamiento' => 'ACTIVO', 'descripcion_tipo_mandamiento' => 'Mandamiento para ejercer presión legal sobre una persona.'],
        ];

        foreach ($tiposMandamientos as $tipo) {
            \App\Models\TipoMandamiento::create($tipo);
        }

        // generame otro seeder para tabla delitos cone stos datos y omite los repetidos:

        $delitos = [
            ['nombre_delito' => 'ESTAFA'],
            ['nombre_delito' => 'PATROCINIO INFIEL RECPTACION'],
            ['nombre_delito' => 'ROBO'],
            ['nombre_delito' => 'RAPTO IMPROPIO'],
            ['nombre_delito' => 'ROBO AGRAVADO'],
            ['nombre_delito' => 'EVASIÓN'],
            ['nombre_delito' => 'EVASIÓN, FAVORECIMIENTO A LA EVASIÓN, INCUMPLIMIENTO DE DEBERES.'],
            ['nombre_delito' => 'ASISTENCIA FAMILIAR'],
            ['nombre_delito' => 'ASESINATO'],
            ['nombre_delito' => 'VIOLACIÓN A NIÑO, NIÑA, ADOLESCENTE'],
            ['nombre_delito' => 'VIOLACIÓN'],
        ];

        foreach ($delitos as $delito) {
            \App\Models\Delito::firstOrCreate($delito);
        }

        // generame otro seeder para tabla juzgados cone stos datos y omite los repetidos:


        $juzgados = [
            ['nombre_juzgado' => 'PRIMERO DE INSTRUCCIÓN EN LO PENAL CAUTELAR'],
            ['nombre_juzgado' => 'FISCALIA'],
            ['nombre_juzgado' => 'JUZGADO PRIMERO DE EJECUCION PENAL'],
            ['nombre_juzgado' => 'JUZGADO DE TRABAJO Y SEGURIDAD SOCIAL No. 2 DEL DPTO DE CBBA.'],
            ['nombre_juzgado' => 'JUZGADO 3RO. DE EJECUCION PENAL'],
            ['nombre_juzgado' => 'JUZGADO DE PARTIDO Y SENTENCIA CHUQUISACA'],
            ['nombre_juzgado' => 'JUZGADO 5TO. PARTIDO DE FAMILIA'],
            ['nombre_juzgado' => 'JUZGADO 4TO DE TRABAJO Y SEGURIDAD SOCIAL'],
            ['nombre_juzgado' => 'JUZGADO PUBLICO DE MATERIA NIÑEZ Y ADOLESCENCIA'],
            ['nombre_juzgado' => 'JUZGADO PUBLICO DE FAMILIA'],
            ['nombre_juzgado' => 'JUZGADO DE INSTRUCCIÓN DE CULPINA - CHUQUISACA'],
            ['nombre_juzgado' => 'TRIBUNAL 7MO. DE SENTENCIA Y SUSTANCIAS CONTROLADAS'],
        ];

        foreach ($juzgados as $juzgado) {
            \App\Models\Juzgado::firstOrCreate($juzgado);
        }

        $paises = [
            ["pais"=> 'Afganistán', "gentilicio"=> 'Afganistán'],
            ["pais"=> 'Albania', "gentilicio"=> 'Albania'],
            ["pais"=> 'Alemania', "gentilicio"=> 'alemán/a'],
            ["pais"=> 'Andorra', "gentilicio"=> 'Andorra'],
            ["pais"=> 'Angola', "gentilicio"=> 'Angola'],
            ["pais"=> 'Anguila', "gentilicio"=> 'Anguila'],
            ["pais"=> 'Antártida', "gentilicio"=> 'Antártida'],
            ["pais"=> 'Antigua y Barbuda', "gentilicio"=> 'Antigua y Barbuda'],
            ["pais"=> 'Arabia Saudita', "gentilicio"=> 'Arabia Saudita'],
            ["pais"=> 'Argelia', "gentilicio"=> 'Argelia'],
            ["pais"=> 'Argentina', "gentilicio"=> 'argentino/a'],
            ["pais"=> 'Armenia', "gentilicio"=> 'Armenia'],
            ["pais"=> 'Aruba', "gentilicio"=> 'Aruba'],
            ["pais"=> 'Australia', "gentilicio"=> 'australiano/a'],
            ["pais"=> 'Austria', "gentilicio"=> 'Austria'],
            ["pais"=> 'Azerbaiyán', "gentilicio"=> 'Azerbaiyán'],
            ["pais"=> 'Bélgica', "gentilicio"=> 'belga'],
            ["pais"=> 'Bahamas', "gentilicio"=> 'Bahamas'],
            ["pais"=> 'Bahrein', "gentilicio"=> 'Bahrein'],
            ["pais"=> 'Bangladesh', "gentilicio"=> 'Bangladesh'],
            ["pais"=> 'Barbados', "gentilicio"=> 'Barbados'],
            ["pais"=> 'Belice', "gentilicio"=> 'Belice'],
            ["pais"=> 'Benín', "gentilicio"=> 'Benín'],
            ["pais"=> 'Bhután', "gentilicio"=> 'Bhután'],
            ["pais"=> 'Bielorrusia', "gentilicio"=> 'Bielorrusia'],
            ["pais"=> 'Birmania', "gentilicio"=> 'Birmania'],
            ["pais"=> 'Bolivia', "gentilicio"=> 'boliviano/a'],
            ["pais"=> 'Bosnia y Herzegovina', "gentilicio"=> 'Bosnia y Herzegovina'],
            ["pais"=> 'Botsuana', "gentilicio"=> 'Botsuana'],
            ["pais"=> 'Brasil', "gentilicio"=> 'brasileño/a'],
            ["pais"=> 'Brunéi', "gentilicio"=> 'Brunéi'],
            ["pais"=> 'Bulgaria', "gentilicio"=> 'Bulgaria'],
            ["pais"=> 'Burkina Faso', "gentilicio"=> 'Burkina Faso'],
            ["pais"=> 'Burundi', "gentilicio"=> 'Burundi'],
            ["pais"=> 'Cabo Verde', "gentilicio"=> 'Cabo Verde'],
            ["pais"=> 'Camboya', "gentilicio"=> 'Camboya'],
            ["pais"=> 'Camerún', "gentilicio"=> 'Camerún'],
            ["pais"=> 'Canadá', "gentilicio"=> 'canadiense'],
            ["pais"=> 'Chad', "gentilicio"=> 'Chad'],
            ["pais"=> 'Chile', "gentilicio"=> 'chileno/a'],
            ["pais"=> 'China', "gentilicio"=> 'chino/a'],
            ["pais"=> 'Chipre', "gentilicio"=> 'Chipre'],
            ["pais"=> 'Ciudad del Vaticano', "gentilicio"=> 'Ciudad del Vaticano'],
            ["pais"=> 'Colombia', "gentilicio"=> 'colombiano/a'],
            ["pais"=> 'Comoras', "gentilicio"=> 'Comoras'],
            ["pais"=> 'República del Congo', "gentilicio"=> 'República del Congo'],
            ["pais"=> 'República Democrática del Congo', "gentilicio"=> 'República Democrática del Congo'],
            ["pais"=> 'Corea del Norte', "gentilicio"=> 'Corea del Norte'],
            ["pais"=> 'Corea del Sur', "gentilicio"=> 'surcoreano/a'],
            ["pais"=> 'Costa de Marfil', "gentilicio"=> 'Costa de Marfil'],
            ["pais"=> 'Costa Rica', "gentilicio"=> 'costarricense'],
            ["pais"=> 'Croacia', "gentilicio"=> 'Croacia'],
            ["pais"=> 'Cuba', "gentilicio"=> 'cubano/a'],
            ["pais"=> 'Curazao', "gentilicio"=> 'Curazao'],
            ["pais"=> 'Dinamarca', "gentilicio"=> 'danés/a'],
            ["pais"=> 'Dominica', "gentilicio"=> 'Dominica'],
            ["pais"=> 'Ecuador', "gentilicio"=> 'ecuatoriano/a'],
            ["pais"=> 'Egipto', "gentilicio"=> 'Egipto'],
            ["pais"=> 'El Salvador', "gentilicio"=> 'salvadoreño/a'],
            ["pais"=> 'Emiratos Árabes Unidos', "gentilicio"=> 'Emiratos Árabes Unidos'],
            ["pais"=> 'Eritrea', "gentilicio"=> 'Eritrea'],
            ["pais"=> 'Eslovaquia', "gentilicio"=> 'Eslovaquia'],
            ["pais"=> 'Eslovenia', "gentilicio"=> 'Eslovenia'],
            ["pais"=> 'España', "gentilicio"=> 'español/a'],
            ["pais"=> 'Estados Unidos de América', "gentilicio"=> 'Estados Unidos de América'],
            ["pais"=> 'Estonia', "gentilicio"=> 'Estonia'],
            ["pais"=> 'Etiopía', "gentilicio"=> 'Etiopía'],
            ["pais"=> 'Filipinas', "gentilicio"=> 'Filipinas'],
            ["pais"=> 'Finlandia', "gentilicio"=> 'finlandés/a'],
            ["pais"=> 'Fiyi', "gentilicio"=> 'Fiyi'],
            ["pais"=> 'Francia', "gentilicio"=> 'francés/a'],
            ["pais"=> 'Gabón', "gentilicio"=> 'Gabón'],
            ["pais"=> 'Gambia', "gentilicio"=> 'Gambia'],
            ["pais"=> 'Georgia', "gentilicio"=> 'Georgia'],
            ["pais"=> 'Ghana', "gentilicio"=> 'Ghana'],
            ["pais"=> 'Gibraltar', "gentilicio"=> 'Gibraltar'],
            ["pais"=> 'Granada', "gentilicio"=> 'Granada'],
            ["pais"=> 'Grecia', "gentilicio"=> 'Grecia'],
            ["pais"=> 'Groenlandia', "gentilicio"=> 'Groenlandia'],
            ["pais"=> 'Guadalupe', "gentilicio"=> 'Guadalupe'],
            ["pais"=> 'Guam', "gentilicio"=> 'Guam'],
            ["pais"=> 'Guatemala', "gentilicio"=> 'Guatemala'],
            ["pais"=> 'Guayana Francesa', "gentilicio"=> 'Guayana Francesa'],
            ["pais"=> 'Guernsey', "gentilicio"=> 'Guernsey'],
            ["pais"=> 'Guinea', "gentilicio"=> 'Guinea'],
            ["pais"=> 'Guinea Ecuatorial', "gentilicio"=> 'Guinea Ecuatorial'],
            ["pais"=> 'Guinea-Bissau', "gentilicio"=> 'Guinea-Bissau'],
            ["pais"=> 'Guyana', "gentilicio"=> 'Guyana'],
            ["pais"=> 'Haití', "gentilicio"=> 'Haití'],
            ["pais"=> 'Honduras', "gentilicio"=> 'Honduras'],
            ["pais"=> 'Hong kong', "gentilicio"=> 'Hong kong'],
            ["pais"=> 'Hungría', "gentilicio"=> 'Hungría'],
            ["pais"=> 'India', "gentilicio"=> 'indio/a'],
            ["pais"=> 'Indonesia', "gentilicio"=> 'Indonesia'],
            ["pais"=> 'Irán', "gentilicio"=> 'Irán'],
            ["pais"=> 'Irak', "gentilicio"=> 'Irak'],
            ["pais"=> 'Irlanda', "gentilicio"=> 'Irlanda'],
            ["pais"=> 'Isla Bouvet', "gentilicio"=> 'Isla Bouvet'],
            ["pais"=> 'Isla de Man', "gentilicio"=> 'Isla de Man'],
            ["pais"=> 'Isla de Navidad', "gentilicio"=> 'Isla de Navidad'],
            ["pais"=> 'Isla Norfolk', "gentilicio"=> 'Isla Norfolk'],
            ["pais"=> 'Islandia', "gentilicio"=> 'Islandia'],
            ["pais"=> 'Islas Bermudas', "gentilicio"=> 'Islas Bermudas'],
            ["pais"=> 'Islas Caimán', "gentilicio"=> 'Islas Caimán'],
            ["pais"=> 'Islas Cocos (Keeling)', "gentilicio"=> 'Islas Cocos (Keeling)'],
            ["pais"=> 'Islas Cook', "gentilicio"=> 'Islas Cook'],
            ["pais"=> 'Islas de Åland', "gentilicio"=> 'Islas de Åland'],
            ["pais"=> 'Islas Feroe', "gentilicio"=> 'Islas Feroe'],
            ["pais"=> 'Islas Georgias del Sur y Sandwich del Sur', "gentilicio"=> 'Islas Georgias del Sur y Sandwich del Sur'],
            ["pais"=> 'Islas Heard y McDonald', "gentilicio"=> 'Islas Heard y McDonald'],
            ["pais"=> 'Islas Maldivas', "gentilicio"=> 'Islas Maldivas'],
            ["pais"=> 'Islas Malvinas', "gentilicio"=> 'Islas Malvinas'],
            ["pais"=> 'Islas Marianas del Norte', "gentilicio"=> 'Islas Marianas del Norte'],
            ["pais"=> 'Islas Marshall', "gentilicio"=> 'Islas Marshall'],
            ["pais"=> 'Islas Pitcairn', "gentilicio"=> 'Islas Pitcairn'],
            ["pais"=> 'Islas Salomón', "gentilicio"=> 'Islas Salomón'],
            ["pais"=> 'Islas Turcas y Caicos', "gentilicio"=> 'Islas Turcas y Caicos'],
            ["pais"=> 'Islas Ultramarinas Menores de Estados Unidos', "gentilicio"=> 'Islas Ultramarinas Menores de Estados Unidos'],
            ["pais"=> 'Islas Vírgenes Británicas', "gentilicio"=> 'Islas Vírgenes Británicas'],
            ["pais"=> 'Islas Vírgenes de los Estados Unidos', "gentilicio"=> 'Islas Vírgenes de los Estados Unidos'],
            ["pais"=> 'Israel', "gentilicio"=> 'Israel'],
            ["pais"=> 'Italia', "gentilicio"=> 'italiano/a'],
            ["pais"=> 'Jamaica', "gentilicio"=> 'Jamaica'],
            ["pais"=> 'Japón', "gentilicio"=> 'japonés/a'],
            ["pais"=> 'Jersey', "gentilicio"=> 'Jersey'],
            ["pais"=> 'Jordania', "gentilicio"=> 'Jordania'],
            ["pais"=> 'Kazajistán', "gentilicio"=> 'Kazajistán'],
            ["pais"=> 'Kenia', "gentilicio"=> 'Kenia'],
            ["pais"=> 'Kirguistán', "gentilicio"=> 'Kirguistán'],
            ["pais"=> 'Kiribati', "gentilicio"=> 'Kiribati'],
            ["pais"=> 'Kuwait', "gentilicio"=> 'Kuwait'],
            ["pais"=> 'Líbano', "gentilicio"=> 'Líbano'],
            ["pais"=> 'Laos', "gentilicio"=> 'Laos'],
            ["pais"=> 'Lesoto', "gentilicio"=> 'Lesoto'],
            ["pais"=> 'Letonia', "gentilicio"=> 'Letonia'],
            ["pais"=> 'Liberia', "gentilicio"=> 'Liberia'],
            ["pais"=> 'Libia', "gentilicio"=> 'Libia'],
            ["pais"=> 'Liechtenstein', "gentilicio"=> 'Liechtenstein'],
            ["pais"=> 'Lituania', "gentilicio"=> 'Lituania'],
            ["pais"=> 'Luxemburgo', "gentilicio"=> 'Luxemburgo'],
            ["pais"=> 'México', "gentilicio"=> 'mexicano/a'],
            ["pais"=> 'Mónaco', "gentilicio"=> 'Mónaco'],
            ["pais"=> 'Macao', "gentilicio"=> 'Macao'],
            ["pais"=> 'Macedônia', "gentilicio"=> 'Macedônia'],
            ["pais"=> 'Madagascar', "gentilicio"=> 'Madagascar'],
            ["pais"=> 'Malasia', "gentilicio"=> 'Malasia'],
            ["pais"=> 'Malawi', "gentilicio"=> 'Malawi'],
            ["pais"=> 'Mali', "gentilicio"=> 'Mali'],
            ["pais"=> 'Malta', "gentilicio"=> 'Malta'],
            ["pais"=> 'Marruecos', "gentilicio"=> 'Marruecos'],
            ["pais"=> 'Martinica', "gentilicio"=> 'Martinica'],
            ["pais"=> 'Mauricio', "gentilicio"=> 'Mauricio'],
            ["pais"=> 'Mauritania', "gentilicio"=> 'Mauritania'],
            ["pais"=> 'Mayotte', "gentilicio"=> 'Mayotte'],
            ["pais"=> 'Micronesia', "gentilicio"=> 'Micronesia'],
            ["pais"=> 'Moldavia', "gentilicio"=> 'Moldavia'],
            ["pais"=> 'Mongolia', "gentilicio"=> 'Mongolia'],
            ["pais"=> 'Montenegro', "gentilicio"=> 'Montenegro'],
            ["pais"=> 'Montserrat', "gentilicio"=> 'Montserrat'],
            ["pais"=> 'Mozambique', "gentilicio"=> 'Mozambique'],
            ["pais"=> 'Namibia', "gentilicio"=> 'Namibia'],
            ["pais"=> 'Nauru', "gentilicio"=> 'Nauru'],
            ["pais"=> 'Nepal', "gentilicio"=> 'Nepal'],
            ["pais"=> 'Nicaragua', "gentilicio"=> 'Nicaragua'],
            ["pais"=> 'Niger', "gentilicio"=> 'Niger'],
            ["pais"=> 'Nigeria', "gentilicio"=> 'Nigeria'],
            ["pais"=> 'Niue', "gentilicio"=> 'Niue'],
            ["pais"=> 'Noruega', "gentilicio"=> 'noruego/a'],
            ["pais"=> 'Nueva Caledonia', "gentilicio"=> 'Nueva Caledonia'],
            ["pais"=> 'Nueva Zelanda', "gentilicio"=> 'Nueva Zelanda'],
            ["pais"=> 'Omán', "gentilicio"=> 'Omán'],
            ["pais"=> 'Países Bajos', "gentilicio"=> 'neerlandés/a'],
            ["pais"=> 'Pakistán', "gentilicio"=> 'Pakistán'],
            ["pais"=> 'Panamá', "gentilicio"=> 'Panamá'],
            ["pais"=> 'Papúa Nueva Guinea', "gentilicio"=> 'Papúa Nueva Guinea'],
            ["pais"=> 'Paraguay', "gentilicio"=> 'paraguayo/a'],
            ["pais"=> 'Perú', "gentilicio"=> 'peruano/a'],
            ["pais"=> 'Polinesia Francesa', "gentilicio"=> 'Polinesia Francesa'],
            ["pais"=> 'Polonia', "gentilicio"=> 'Polonia'],
            ["pais"=> 'Portugal', "gentilicio"=> 'portugués/a'],
            ["pais"=> 'Puerto Rico', "gentilicio"=> 'Puerto Rico'],
            ["pais"=> 'Qatar', "gentilicio"=> 'Qatar'],
            ["pais"=> 'Reino Unido', "gentilicio"=> 'británico/a'],
            ["pais"=> 'República Centroafricana', "gentilicio"=> 'República Centroafricana'],
            ["pais"=> 'República Checa', "gentilicio"=> 'República Checa'],
            ["pais"=> 'República Dominicana', "gentilicio"=> 'dominicano/a'],
            ["pais"=> 'República de Sudán del Sur', "gentilicio"=> 'República de Sudán del Sur'],
            ["pais"=> 'Reunión', "gentilicio"=> 'Reunión'],
            ["pais"=> 'Ruanda', "gentilicio"=> 'Ruanda'],
            ["pais"=> 'Rumanía', "gentilicio"=> 'Rumanía'],
            ["pais"=> 'Rusia', "gentilicio"=> 'ruso/a'],
            ["pais"=> 'Sahara Occidental', "gentilicio"=> 'Sahara Occidental'],
            ["pais"=> 'Samoa', "gentilicio"=> 'Samoa'],
            ["pais"=> 'Samoa Americana', "gentilicio"=> 'Samoa Americana'],
            ["pais"=> 'San Bartolomé', "gentilicio"=> 'San Bartolomé'],
            ["pais"=> 'San Cristóbal y Nieves', "gentilicio"=> 'San Cristóbal y Nieves'],
            ["pais"=> 'San Marino', "gentilicio"=> 'San Marino'],
            ["pais"=> 'San Martín (Francia)', "gentilicio"=> 'San Martín (Francia)'],
            ["pais"=> 'San Pedro y Miquelón', "gentilicio"=> 'San Pedro y Miquelón'],
            ["pais"=> 'San Vicente y las Granadinas', "gentilicio"=> 'San Vicente y las Granadinas'],
            ["pais"=> 'Santa Elena', "gentilicio"=> 'Santa Elena'],
            ["pais"=> 'Santa Lucía', "gentilicio"=> 'Santa Lucía'],
            ["pais"=> 'Santo Tomé y Príncipe', "gentilicio"=> 'Santo Tomé y Príncipe'],
            ["pais"=> 'Senegal', "gentilicio"=> 'Senegal'],
            ["pais"=> 'Serbia', "gentilicio"=> 'Serbia'],
            ["pais"=> 'Seychelles', "gentilicio"=> 'Seychelles'],
            ["pais"=> 'Sierra Leona', "gentilicio"=> 'Sierra Leona'],
            ["pais"=> 'Singapur', "gentilicio"=> 'Singapur'],
            ["pais"=> 'Sint Maarten', "gentilicio"=> 'Sint Maarten'],
            ["pais"=> 'Siria', "gentilicio"=> 'Siria'],
            ["pais"=> 'Somalia', "gentilicio"=> 'Somalia'],
            ["pais"=> 'Sri lanka', "gentilicio"=> 'Sri lanka'],
            ["pais"=> 'Sudáfrica', "gentilicio"=> 'sudafricano/a'],
            ["pais"=> 'Sudán', "gentilicio"=> 'Sudán'],
            ["pais"=> 'Suecia', "gentilicio"=> 'sueco/a'],
            ["pais"=> 'Suiza', "gentilicio"=> 'suizo/a'],
            ["pais"=> 'Surinám', "gentilicio"=> 'Surinám'],
            ["pais"=> 'Svalbard y Jan Mayen', "gentilicio"=> 'Svalbard y Jan Mayen'],
            ["pais"=> 'Swazilandia', "gentilicio"=> 'Swazilandia'],
            ["pais"=> 'Tayikistán', "gentilicio"=> 'Tayikistán'],
            ["pais"=> 'Tailandia', "gentilicio"=> 'Tailandia'],
            ["pais"=> 'Taiwán', "gentilicio"=> 'Taiwán'],
            ["pais"=> 'Tanzania', "gentilicio"=> 'Tanzania'],
            ["pais"=> 'Territorio Británico del Océano Índico', "gentilicio"=> 'Territorio Británico del Océano Índico'],
            ["pais"=> 'Territorios Australes y Antárticas Franceses', "gentilicio"=> 'Territorios Australes y Antárticas Franceses'],
            ["pais"=> 'Timor Oriental', "gentilicio"=> 'Timor Oriental'],
            ["pais"=> 'Togo', "gentilicio"=> 'Togo'],
            ["pais"=> 'Tokelau', "gentilicio"=> 'Tokelau'],
            ["pais"=> 'Tonga', "gentilicio"=> 'Tonga'],
            ["pais"=> 'Trinidad y Tobago', "gentilicio"=> 'Trinidad y Tobago'],
            ["pais"=> 'Tunez', "gentilicio"=> 'Tunez'],
            ["pais"=> 'Turkmenistán', "gentilicio"=> 'Turkmenistán'],
            ["pais"=> 'Turquía', "gentilicio"=> 'turco/a'],
            ["pais"=> 'Tuvalu', "gentilicio"=> 'Tuvalu'],
            ["pais"=> 'Ucrania', "gentilicio"=> 'Ucrania'],
            ["pais"=> 'Uganda', "gentilicio"=> 'Uganda'],
            ["pais"=> 'Uruguay', "gentilicio"=> 'uruguayo/a'],
            ["pais"=> 'Uzbekistán', "gentilicio"=> 'Uzbekistán'],
            ["pais"=> 'Vanuatu', "gentilicio"=> 'Vanuatu'],
            ["pais"=> 'Venezuela', "gentilicio"=> 'venezolano/a'],
            ["pais"=> 'Vietnam', "gentilicio"=> 'Vietnam'],
            ["pais"=> 'Wallis y Futuna', "gentilicio"=> 'Wallis y Futuna'],
            ["pais"=> 'Yemen', "gentilicio"=> 'Yemen'],
            ["pais"=> 'Yibuti', "gentilicio"=> 'Yibuti'],
            ["pais"=> 'Zambia', "gentilicio"=> 'Zambia'],
            ["pais"=> 'Zimbabue', "gentilicio"=> 'Zimbabue'],
        ];

        // insertar en un batch todo de golpe
        \App\Models\Pais::insert($paises);
    }
}
